version: 2

project_name: pitrrwnd

before:
  hooks:
    - go mod tidy

builds:
  - id: pitr
    main: ./cmd/pitr
    binary: pitr
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_arm64

archives:
  - id: default
    ids:
      - pitr
    name_template: >-
      pitr-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README*.md
      - VERSION
      - CHANGELOG.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'
      - '^ci:'

release:
  draft: false
  prerelease: auto
